"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import type { CaseStudy } from "@/lib/db";

export default function CaseStudyPortfolio({ items }: { items: CaseStudy[] }) {
  const [filter, setFilter] = useState("All case studies");
  const industries = [...new Set(items.map(item => item.industry).filter(Boolean))];
  const featured = items[0];
  const featuredImage = featured?.cover_image_url || featured?.images[0]?.url;
  const visible = items.filter(item => filter === "All case studies" || item.industry === filter);
  return <>
    <div className="cp-filters" role="group" aria-label="Filter case studies by industry">{["All case studies", ...industries].map(label => <button key={label} type="button" aria-pressed={filter === label} onClick={() => setFilter(label)}>{label}</button>)}</div>
    {featured && filter === "All case studies" && <section className="cp-featured cp-section" aria-label="Featured case study"><div className="cp-featured-copy"><p className="cp-badge"><span />Featured success story</p><p className="cp-eyebrow">{featured.industry}</p><h2>{featured.title}</h2><p className="cp-description">{featured.excerpt}</p><div className="cp-feature-metrics">{featured.metrics.map((metric, i) => <div key={`${metric.label}-${i}`}><p>{metric.label}</p><strong>{metric.value}</strong></div>)}</div><p className="cp-eyebrow">Built for sustainable growth</p><ul className="cp-checks">{featured.phases.slice(0, 3).map((phase, i) => <li key={i}>{phase.title}</li>)}</ul><Link className="cp-button" href={`/case-studies/${featured.slug}`}>Read the full case study <span>↗</span></Link></div><div className="cp-featured-proof">{featuredImage ? <Image src={featuredImage} alt={`${featured.client_name || featured.title} results dashboard`} width={1000} height={600} sizes="(max-width: 700px) 100vw, 50vw" unoptimized /> : <div className="cp-proof-summary"><p className="cp-eyebrow">The approach</p><h3>{featured.phases[0]?.title || "A retention system built around the brand"}</h3><p className="cp-description">{featured.solution || featured.challenge || featured.excerpt}</p></div>}{featured.results && <div className="cp-proof-caption"><span className="cp-icon">↗</span><p>{featured.results}</p></div>}<span className="cp-evidence-label">Real account data. The work behind the growth.</span></div></section>}
    <section className="cp-section" id="results"><div className="cp-section-heading"><div><p className="cp-eyebrow">Performance across industries</p><h2>Proven growth.<br />Built around each brand.</h2></div><p>Different products. Different customers. The same commitment to thoughtful strategy and measurable results.</p></div><p className="cp-result-count" role="status" aria-live="polite">{visible.length} {visible.length === 1 ? "case study" : "case studies"}{filter !== "All case studies" ? ` · ${filter}` : ""}</p><div className="cp-case-grid">{visible.map(item => <article className="cp-case" key={item.id}><div className="cp-case-head"><span className="cp-icon">↗</span><div><strong>{item.client_name || "Client success story"}</strong><p>{item.industry || "DTC ecommerce"}</p></div>{item.project_period && <span className="cp-period">{item.project_period}</span>}</div><h3><Link href={`/case-studies/${item.slug}`}>{item.title}</Link></h3><p className="cp-case-excerpt">{item.excerpt}</p><div className="cp-case-evidence">{[...(item.cover_image_url ? [{ url: item.cover_image_url, caption: `${item.title} overview` }] : []), ...item.images].map((image, index) => <figure key={`${image.url}-${index}`}><Image src={image.url} alt={image.caption || `${item.title} results ${index + 1}`} width={1400} height={900} sizes="(max-width: 700px) 100vw, 50vw" unoptimized />{image.caption && <figcaption>{image.caption}</figcaption>}</figure>)}</div><div className="cp-card-metrics">{item.metrics.slice(0, 3).map((metric, i) => <div key={`${metric.label}-${i}`}><p>{metric.label}</p><strong>{metric.value}</strong></div>)}</div><ul className="cp-checks">{item.phases.slice(0, 2).map((phase, i) => <li key={i}>{phase.title}</li>)}</ul><div className="cp-case-foot"><span>Digital Supremacy</span><Link href={`/case-studies/${item.slug}`}>Read case study ↗</Link></div></article>)}</div>{items.length === 0 && <p className="cp-empty">New case studies are being prepared. In the meantime, <Link href="/#cases">explore our client results</Link>.</p>}</section>
  </>;
}
